// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8e3oKydZInZcf9Z5E7y8p_hV2ypw7YDE',
    appId: '1:800821195486:web:0f705f3e141a0ae480084f',
    messagingSenderId: '800821195486',
    projectId: 'blog-travel-be309',
    authDomain: 'blog-travel-be309.firebaseapp.com',
    storageBucket: 'blog-travel-be309.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU56JHq8_dq7yKJ8ghaJm4fypYi8q2qCs',
    appId: '1:800821195486:android:797551850477bfac80084f',
    messagingSenderId: '800821195486',
    projectId: 'blog-travel-be309',
    storageBucket: 'blog-travel-be309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm5GvPwopbJ1_o3BQQqGN52uU12DZL3TY',
    appId: '1:800821195486:ios:23f10014c49b138c80084f',
    messagingSenderId: '800821195486',
    projectId: 'blog-travel-be309',
    storageBucket: 'blog-travel-be309.firebasestorage.app',
    iosBundleId: 'com.example.blogTravelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm5GvPwopbJ1_o3BQQqGN52uU12DZL3TY',
    appId: '1:800821195486:ios:23f10014c49b138c80084f',
    messagingSenderId: '800821195486',
    projectId: 'blog-travel-be309',
    storageBucket: 'blog-travel-be309.firebasestorage.app',
    iosBundleId: 'com.example.blogTravelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8e3oKydZInZcf9Z5E7y8p_hV2ypw7YDE',
    appId: '1:800821195486:web:1939de92d025059780084f',
    messagingSenderId: '800821195486',
    projectId: 'blog-travel-be309',
    authDomain: 'blog-travel-be309.firebaseapp.com',
    storageBucket: 'blog-travel-be309.firebasestorage.app',
  );
}
